---
- name: Started and Enabled chronyd
  service: 
    name: chronyd
    enabled: true 
    state: started

- name: Restarted firewalld
  service: 
    name: firewalld 
    state: restarted

- name: Started and Enabled nginx
  service: 
    name: nginx 
    enabled: true 
    state: started

- name: Started and Enabled php-fpm
  service: 
    name: php-fpm
    enabled: true 
    state: started

- name: Restarted nginx
  service:
    name: nginx 
    state: restarted